name: .checkout-sign

on:
  workflow_call:
    secrets: 
      scribe-client-id:
        required: false
      scribe-client-secret:
        required: false

jobs:
  checkout-sign:
    name: Checkout Sign
    timeout-minutes: 3
    strategy:
      matrix:
        platform: ["ubuntu-latest"]
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Scribe Enable
        run: |
          export KO_TAG=$(basename "${{ github.ref }}")
          echo "KO_TAG=$KO_TAG" >> $GITHUB_ENV
          if [ "${{ secrets.scribe-client-id }}" == "" ]; then
            echo "Scribe is disabled"
            echo "SCRIBE_ENABLE=false" >> "${GITHUB_ENV}"
          else
            echo "Scribe is enabled"
            echo "SCRIBE_ENABLE=true" >> "${GITHUB_ENV}"
          fi

      - name: Evidence - Sign Source SBOM
        id: attest-cdx-source
        uses: scribe-security/action-bom@master
        with:
           target: git:.
           verbose: 2
           format: attest
           product-key: ${{ env.GITHUB_REPOSITORY }}
           product-version: ${{ env.KO_TAG }}
           scribe-enable: ${{ env.SCRIBE_ENABLE }}
           scribe-client-id: ${{ secrets.scribe-client-id }}
           scribe-client-secret: ${{ secrets.scribe-client-secret }}
           git-tag: 

      - name: Archive evidence - Github Artifact
        uses: actions/upload-artifact@v3
        with:
          name: checkout-evidence
          path: |
            ${{ steps.attest-cdx-source.outputs.OUTPUT_PATH }}
          retention-days: 1